In [13]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
df=pd.read_csv('PAMAP_features.csv')
df=df.drop(columns='Unnamed: 0')
print(df['sub_id'].value_counts())
print(df['activity_id'].value_counts())
df=df.drop(columns=['sub_id', 'activity_id'])
label=LabelEncoder()
df['act_lavel']=label.fit_transform(df['act_level'])
df

sub_id
5    1651
2    1618
8    1576
6    1556
1    1518
7    1430
4    1353
3    1042
9      29
Name: count, dtype: int64
activity_id
17    1539
4     1525
3     1220
1     1203
7     1196
2     1162
16    1099
6     1035
5      593
12     522
13     428
24     251
Name: count, dtype: int64


act_level     hr_mean  hr_mean_normal    hr_std  hr_std_normal  \
0         light   87.000000        1.175676  0.000000   7.105427e-15   
1      moderate  124.605469        1.683858  0.927920   1.253946e-02   
2      vigorous  113.493430        1.891557  2.315888   3.859813e-02   
3         light   82.513672        1.375228  0.492657   8.210948e-03   
4         light   73.000000        1.106061  0.000000   7.327472e-15   
...         ...         ...             ...       ...            ...   
11768     light   82.582031        1.376367  0.930285   1.550475e-02   
11769     light   76.998047        1.132324  0.806906   1.186626e-02   
11770  moderate   93.445312        1.557422  0.493415   8.223580e-03   
11771  moderate  129.160156        1.745408  0.361877   4.890232e-03   
11772  moderate  142.234375        1.922086  1.714464   2.316843e-02   

       hand_tmp_mean  hand_tmp_std  hand_acc_x_mean  hand_acc_x_std  \
0          34.375000      0.000000        -1.165524        2.383779   
1          31.875000      0.000000       -12.040995        3.734766   
2          32.500000      0.000000        -3.723040       10.188184   
3          33.812500      0.000000        -3.618932        1.935690   
4          34.437500      0.000000        -9.275877        0.082824   
...              ...           ...              ...             ...   
11768      33.525635      0.030741        -4.306831        0.087374   
11769      32.083130      0.029390        -1.545991        0.086820   
11770      31.750000      0.000000       -10.034760        1.780491   
11771      30.465576      0.031088        -8.275569        3.245008   
11772      32.173340      0.026163        -3.077000        3.850697   

       hand_acc_y_mean  ...  ankle_acc_xz_cor  hand_gyr_xy_cor  \
0             3.381285  ...          0.233251        -0.472662   
1             3.069947  ...         -0.119772        -0.287380   
2            11.705779  ...          0.025673        -0.265566   
3             0.542981  ...          0.724061        -0.196728   
4             1.006239  ...         -0.001651        -0.060776   
...                ...  ...               ...              ...   
11768         1.634235  ...          0.193950        -0.354026   
11769         3.379703  ...          0.135629         0.056979   
11770         3.100475  ...         -0.404942         0.520845   
11771         6.196727  ...         -0.136336        -0.147614   
11772         3.495658  ...          0.200755        -0.081262   

       hand_gyr_yz_cor  hand_gyr_xz_cor  chest_gyr_xy_cor  chest_gyr_yz_cor  \
0             0.335516        -0.377507         -0.290138         -0.779952   
1            -0.230390        -0.491314          0.011124         -0.799319   
2             0.824691        -0.121345         -0.004923         -0.317761   
3             0.315984        -0.380337          0.284190         -0.109078   
4             0.165672         0.311760         -0.272620         -0.014943   
...                ...              ...               ...               ...   
11768         0.175876        -0.172933          0.184131         -0.274344   
11769         0.008235         0.001093         -0.203294         -0.097797   
11770        -0.951838        -0.561901         -0.169119          0.299434   
11771        -0.344375        -0.329746         -0.024487         -0.536806   
11772         0.130816        -0.278256         -0.254757         -0.723943   

       chest_gyr_xz_cor  ankle_gyr_xy_cor  ankle_gyr_yz_cor  ankle_gyr_xz_cor  
0              0.071855         -0.305959         -0.003001         -0.638866  
1             -0.135736         -0.653133         -0.654575          0.391363  
2             -0.202148         -0.660278         -0.528138          0.402147  
3             -0.071734         -0.177813          0.237828         -0.729771  
4             -0.191610         -0.261158          0.066954          0.057685  
...                 ...               ...               ...       

In [8]:
X=df.drop('act_level',axis=1)
X.head()

hr_mean  hr_mean_normal    hr_std  hr_std_normal  hand_tmp_mean  \
0   87.000000        1.175676  0.000000   7.105427e-15        34.3750   
1  124.605469        1.683858  0.927920   1.253946e-02        31.8750   
2  113.493430        1.891557  2.315888   3.859813e-02        32.5000   
3   82.513672        1.375228  0.492657   8.210948e-03        33.8125   
4   73.000000        1.106061  0.000000   7.327472e-15        34.4375   

   hand_tmp_std  hand_acc_x_mean  hand_acc_x_std  hand_acc_y_mean  \
0           0.0        -1.165524        2.383779         3.381285   
1           0.0       -12.040995        3.734766         3.069947   
2           0.0        -3.723040       10.188184        11.705779   
3           0.0        -3.618932        1.935690         0.542981   
4           0.0        -9.275877        0.082824         1.006239   

   hand_acc_y_std  ...  ankle_acc_xz_cor  hand_gyr_xy_cor  hand_gyr_yz_cor  \
0        2.582771  ...          0.233251        -0.472662         0.335516   
1        2.591651  ...         -0.119772        -0.287380        -0.230390   
2       17.220389  ...          0.025673        -0.265566         0.824691   
3        2.907890  ...          0.724061        -0.196728         0.315984   
4        0.153816  ...         -0.001651        -0.060776         0.165672   

   hand_gyr_xz_cor  chest_gyr_xy_cor  chest_gyr_yz_cor  chest_gyr_xz_cor  \
0        -0.377507         -0.290138         -0.779952          0.071855   
1        -0.491314          0.011124         -0.799319         -0.135736   
2        -0.121345         -0.004923         -0.317761         -0.202148   
3        -0.380337          0.284190         -0.109078         -0.071734   
4         0.311760         -0.272620         -0.014943         -0.191610   

   ankle_gyr_xy_cor  ankle_gyr_yz_cor  ankle_gyr_xz_cor  
0         -0.305959         -0.003001         -0.638866  
1         -0.653133         -0.654575          0.391363  
2         -0.660278         -0.528138          0.402147  
3         -0.177813          0.237828         -0.729771  
4         -0.261158          0.066954          0.057685  

[5 rows x 64 columns]

In [10]:
y=df['act_level']
y.value_counts()

act_level
moderate    5283
light       5124
vigorous    1366
Name: count, dtype: int64

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import *
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
              precision    recall  f1-score   support

       light       1.00      0.99      0.99      1033
    moderate       0.99      0.99      0.99      1034
    vigorous       0.98      0.98      0.98       288

    accuracy                           0.99      2355
   macro avg       0.99      0.99      0.99      2355
weighted avg       0.99      0.99      0.99      2355

[[1025    7    1]
 [   5 1023    6]
 [   0    5  283]]


In [22]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
              precision    recall  f1-score   support

       light       1.00      0.99      0.99      1033
    moderate       0.99      0.99      0.99      1034
    vigorous       0.98      0.98      0.98       288

    accuracy                           0.99      2355
   macro avg       0.99      0.99      0.99      2355
weighted avg       0.99      0.99      0.99      2355

[[1025    7    1]
 [   5 1023    6]
 [   0    5  283]]


In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(classification_report(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
              precision    recall  f1-score   support

       light       1.00      1.00      1.00      1033
    moderate       1.00      1.00      1.00      1034
    vigorous       1.00      0.99      1.00       288

    accuracy                           1.00      2355
   macro avg       1.00      1.00      1.00      2355
weighted avg       1.00      1.00      1.00      2355

[[1033    0    0]
 [   3 1031    0]
 [   0    2  286]]


In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print(classification_report(y_test,pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
              precision    recall  f1-score   support

       light       0.99      0.99      0.99      1033
    moderate       0.99      0.99      0.99      1034
    vigorous       0.98      0.99      0.98       288

    accuracy                           0.99      2355
   macro avg       0.99      0.99      0.99      2355
weighted avg       0.99      0.99      0.99      2355

[[1024    6    3]
 [  10 1021    3]
 [   0    3  285]]


In [47]:
df=pd.read_csv('PAMAP_features.csv', index_col=0)
df.index
df=df.drop(columns=['sub_id', 'act_level'])
label=LabelEncoder()
df['activity_id']=label.fit_transform(df['activity_id'])
df

activity_id     hr_mean  hr_mean_normal    hr_std  hr_std_normal  \
3006            10   87.000000        1.175676  0.000000   7.105427e-15   
3497             3  124.605469        1.683858  0.927920   1.253946e-02   
14495            4  113.493430        1.891557  2.315888   3.859813e-02   
13278           10   82.513672        1.375228  0.492657   8.210948e-03   
14969            2   73.000000        1.106061  0.000000   7.327472e-15   
...            ...         ...             ...       ...            ...   
10708            1   82.582031        1.376367  0.930285   1.550475e-02   
4870             1   76.998047        1.132324  0.806906   1.186626e-02   
11822            3   93.445312        1.557422  0.493415   8.223580e-03   
3866             6  129.160156        1.745408  0.361877   4.890232e-03   
3450             8  142.234375        1.922086  1.714464   2.316843e-02   

       hand_tmp_mean  hand_tmp_std  hand_acc_x_mean  hand_acc_x_std  \
3006       34.375000      0.000000        -1.165524        2.383779   
3497       31.875000      0.000000       -12.040995        3.734766   
14495      32.500000      0.000000        -3.723040       10.188184   
13278      33.812500      0.000000        -3.618932        1.935690   
14969      34.437500      0.000000        -9.275877        0.082824   
...              ...           ...              ...             ...   
10708      33.525635      0.030741        -4.306831        0.087374   
4870       32.083130      0.029390        -1.545991        0.086820   
11822      31.750000      0.000000       -10.034760        1.780491   
3866       30.465576      0.031088        -8.275569        3.245008   
3450       32.173340      0.026163        -3.077000        3.850697   

       hand_acc_y_mean  ...  ankle_acc_xz_cor  hand_gyr_xy_cor  \
3006          3.381285  ...          0.233251        -0.472662   
3497          3.069947  ...         -0.119772        -0.287380   
14495        11.705779  ...          0.025673        -0.265566   
13278         0.542981  ...          0.724061        -0.196728   
14969         1.006239  ...         -0.001651        -0.060776   
...                ...  ...               ...              ...   
10708         1.634235  ...          0.193950        -0.354026   
4870          3.379703  ...          0.135629         0.056979   
11822         3.100475  ...         -0.404942         0.520845   
3866          6.196727  ...         -0.136336        -0.147614   
3450          3.495658  ...          0.200755        -0.081262   

       hand_gyr_yz_cor  hand_gyr_xz_cor  chest_gyr_xy_cor  chest_gyr_yz_cor  \
3006          0.335516        -0.377507         -0.290138         -0.779952   
3497         -0.230390        -0.491314          0.011124         -0.799319   
14495         0.824691        -0.121345         -0.004923         -0.317761   
13278         0.315984        -0.380337          0.284190         -0.109078   
14969         0.165672         0.311760         -0.272620         -0.014943   
...                ...              ...               ...               ...   
10708         0.175876        -0.172933          0.184131         -0.274344   
4870          0.008235         0.001093         -0.203294         -0.097797   
11822        -0.951838        -0.561901         -0.169119          0.299434   
3866         -0.344375        -0.329746         -0.024487         -0.536806   
3450          0.130816        -0.278256         -0.254757         -0.723943   

       chest_gyr_xz_cor  ankle_gyr_xy_cor  ankle_gyr_yz_cor  ankle_gyr_xz_cor  
3006           0.071855         -0.305959         -0.003001         -0.638866  
3497          -0.135736         -0.653133         -0.654575          0.391363  
14495         -0.202148         -0.660278         -0.528138          0.402147  
13278         -0.071734         -0.177813          0.237828         -0.729771  
14969         -0.191610         -0.261158          0.066954          0.057685  
...                 ...        

In [58]:
X=df.drop('activity_id', axis=1)
y=df['activity_id']


In [51]:
Y = pd.get_dummies(y).values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [59]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam
import numpy as np

model = Sequential()

model.add(Dense(192,input_shape=(64,),activation='relu'))
model.add(Dense(48,activation='relu'))
model.add(Dense(24,activation='relu'))
model.add(Dense(12,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()


Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_28 (Dense)            (None, 192)               12480     
                                                                 
 dense_29 (Dense)            (None, 48)                9264      
                                                                 
 dense_30 (Dense)            (None, 24)                1176      
                                                                 
 dense_31 (Dense)            (None, 12)                300       
                                                                 
Total params: 23220 (90.70 KB)
Trainable params: 23220 (90.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [60]:

model_history=model.fit(x=X_train, y=y_train, epochs=30, batch_size=64,validation_split= 0.1)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
133/133 [==============================] - 1s 2ms/step - loss: 1.4879 - accuracy: 0.5905 - val_loss: 0.5988 - val_accuracy: 0.8567
Epoch 2/30
133/133 [==============================] - 0s 942us/step - loss: 0.3883 - accuracy: 0.9071 - val_loss: 0.2412 - val_accuracy: 0.9427
Epoch 3/30
133/133 [==============================] - 0s 908us/step - loss: 0.2049 - accuracy: 0.9475 - val_loss: 0.1451 - val_accuracy: 0.9607
Epoch 4/30
133/133 [==============================] - 0s 936us/step - loss: 0.1491 - accuracy: 0.9585 - val_loss: 0.1318 - val_accuracy: 0.9597
Epoch 5/30
133/133 [==============================] - 0s 932us/step - loss: 0.1204 - accuracy: 0.9645 - val_loss: 0.0959 - val_accuracy: 0.9766
Epoch 6/30
133/133 [==============================] - 0s 895us/step - loss: 0.1062 - accuracy: 0.9685 - val_loss: 0.0907 - val_accuracy: 0.9724
Epoch 7/30
133/133 [==============================] - 0s 906us/step - loss: 0.0835 - accuracy: 0.9733 - val_loss: 0.0978 - val_accuracy: 0

In [62]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       243
           1       1.00      1.00      1.00       227
           2       1.00      1.00      1.00       230
           3       1.00      1.00      1.00       318
           4       1.00      1.00      1.00       116
           5       1.00      1.00      1.00       206
           6       1.00      1.00      1.00       239
           7       1.00      1.00      1.00       124
           8       1.00      1.00      1.00        89
           9       1.00      1.00      1.00       210
          10       1.00      1.00      1.00       307
          11       1.00      1.00      1.00        46

    accuracy                           1.00      2355
   macro avg       1.00      1.00      1.00      2355
weighted avg       1.00      1.00      1.00      2355

[[243   0   0   0   0   0   0   0   0   0   0   0]
 [  0 227   0   0   0   0   0   0   0   0   0   0]
 [  0   0 230   0   0   0   0  