In [58]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
import pandas as pd

digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)

#Y = pd.get_dummies(y).values
X_train, X_test, y_train, y_test = train_test_split(
    data, digits.target, test_size=0.2)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(f"{metrics.classification_report(y_test, y_pred)}\n")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       0.94      1.00      0.97        31
           2       1.00      1.00      1.00        30
           3       1.00      1.00      1.00        43
           4       1.00      0.95      0.98        42
           5       0.96      1.00      0.98        24
           6       1.00      1.00      1.00        35
           7       0.98      1.00      0.99        43
           8       0.97      0.94      0.95        32
           9       1.00      0.97      0.99        38

    accuracy                           0.99       360
   macro avg       0.98      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360




In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import *
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [5]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)
pred_lr = lr.predict(X_test)
print ("\n--- Linear Regression MSE ---")
mse = mean_squared_error(y_test, pred_lr)
print("Mean Squared Error:", mse)


--- Linear Regression MSE ---
Mean Squared Error: 4.044405616447345


In [47]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test.argmax(axis=1), pred_dt.argmax(axis=1)))


--- Decision Tree Classifier ---
0.8694444444444445
[[40  0  0  0  1  0  0  0  0  0]
 [ 0 33  0  1  1  0  0  1  2  1]
 [ 0  0 27  1  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  0  1]
 [ 0  2  0  0 27  1  0  1  1  0]
 [ 0  0  0  0  1 35  1  0  1  1]
 [ 0  0  0  1  3  0 34  0  0  0]
 [ 0  1  1  0  1  1  0 27  2  0]
 [ 0  2  4  1  1  2  0  0 31  2]
 [ 1  1  0  1  0  1  0  0  3 28]]


In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test.argmax(axis=1), pred.argmax(axis=1)))




--- Radom Forest ---
0.975


AxisError: axis 1 is out of bounds for array of dimension 1

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9694444444444444
[[42  0  0  0  0  0  0  0  0  0]
 [ 0 31  0  0  0  0  0  0  0  0]
 [ 0  0 28  2  0  0  0  0  0  0]
 [ 0  0  1 41  0  0  0  0  0  1]
 [ 1  0  0  0 38  0  0  0  1  2]
 [ 0  0  0  0  0 24  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  1  0  0  0 41  0  1]
 [ 0  0  0  0  0  0  0  0 32  0]
 [ 0  0  0  0  0  0  0  1  0 37]]


In [50]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(256,input_shape=(64,),activation='tanh'))
model.add(Dense(64,activation='tanh'))
model.add(Dense(16,activation='tanh'))
model.add(Dense(10,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 256)               16640     
                                                                 
 dense_17 (Dense)            (None, 64)                16448     
                                                                 
 dense_18 (Dense)            (None, 16)                1040      
                                                                 
 dense_19 (Dense)            (None, 10)                170       
                                                                 
Total params: 34298 (133.98 KB)
Trainable params: 34298 (133.98 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [62]:
y_train = pd.get_dummies(y_train).values
y_test = pd.get_dummies(y_test).values
model_history=model.fit(x=X_train, y=y_train, epochs=30, batch_size=64,validation_split= 0.1)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
21/21 [==============================] - 0s 5ms/step - loss: 0.0393 - accuracy: 0.9946 - val_loss: 0.0451 - val_accuracy: 0.9931
Epoch 2/30
21/21 [==============================] - 0s 3ms/step - loss: 0.0316 - accuracy: 0.9969 - val_loss: 0.0599 - val_accuracy: 0.9931
Epoch 3/30
21/21 [==============================] - 0s 3ms/step - loss: 0.0253 - accuracy: 0.9992 - val_loss: 0.0446 - val_accuracy: 0.9931
Epoch 4/30
21/21 [==============================] - 0s 3ms/step - loss: 0.0204 - accuracy: 0.9985 - val_loss: 0.0554 - val_accuracy: 0.9931
Epoch 5/30
21/21 [==============================] - 0s 3ms/step - loss: 0.0173 - accuracy: 0.9992 - val_loss: 0.0372 - val_accuracy: 0.9931
Epoch 6/30
21/21 [==============================] - 0s 2ms/step - loss: 0.0143 - accuracy: 1.0000 - val_loss: 0.0433 - val_accuracy: 0.9931
Epoch 7/30
21/21 [==============================] - 0s 2ms/step - loss: 0.0131 - accuracy: 1.0000 - val_loss: 0.0383 - val_accuracy: 0.9931
Epoch 8/30
21/21 [==

In [63]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       1.00      1.00      1.00        31
           2       1.00      1.00      1.00        30
           3       1.00      1.00      1.00        43
           4       1.00      0.98      0.99        42
           5       1.00      1.00      1.00        24
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        43
           8       0.97      1.00      0.98        32
           9       1.00      1.00      1.00        38

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

[[42  0  0  0  0  0  0  0  0  0]
 [ 0 31  0  0  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0  0  0]
 [ 0  0  0 43  0  0  0  0  0  0]
 [ 0  0  0  0 41  0  0  0  1  0]
 [ 0  0  0  0  0 24  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0

In [20]:
X_test.shape

(360, 64)

In [27]:
model.predict(X_test)

12/12 [==============================] - 0s 885us/step


array([[1.9250115e-04, 2.1157485e-04, 6.0930592e-04, ..., 6.5763752e-06,
        9.0508729e-05, 4.3204942e-05],
       [4.7750941e-06, 8.0445735e-04, 6.5510283e-04, ..., 1.1065172e-03,
        2.2088310e-04, 1.2786385e-03],
       [2.5955915e-05, 9.9563271e-01, 5.9052801e-04, ..., 2.4198787e-05,
        9.0038497e-04, 5.2732012e-05],
       ...,
       [6.1798596e-06, 1.2693080e-03, 3.5070307e-03, ..., 5.0151171e-03,
        2.7034007e-04, 8.1821840e-04],
       [1.9027966e-03, 5.8030855e-05, 2.4718331e-05, ..., 5.1768799e-03,
        2.1811592e-04, 4.7917757e-04],
       [4.6690536e-04, 1.3452390e-04, 1.3449760e-03, ..., 1.5354564e-05,
        2.1692584e-04, 3.2470787e-05]], dtype=float32)

In [29]:
X_test[1]

array([ 0.,  0.,  7., 15., 15.,  2.,  0.,  0.,  0.,  0., 13.,  6., 12.,
        6.,  0.,  0.,  0.,  0.,  0.,  0., 15.,  2.,  0.,  0.,  0.,  0.,
        0., 13., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  8., 15., 12.,  0.,
        0.,  0.,  3.,  7.,  0.,  2., 15.,  1.,  0.,  0.,  2., 15.,  6.,
        6., 16.,  1.,  0.,  0.,  0.,  4., 15., 16.,  7.,  0.,  0.])

In [26]:
X_test

array([[ 0.,  0.,  2., ..., 16., 12.,  1.],
       [ 0.,  0.,  7., ...,  7.,  0.,  0.],
       [ 0.,  0.,  3., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  9., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  2., ..., 14.,  4.,  0.]])